robosnake:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_0
    pid: {p: 33.0, i: 1.2, d: 0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 33.0, i: 1.2, d: 0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 33.0, i: 1.2, d: 0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 33.0, i: 1.2, d: 0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 33.0, i: 1.2, d: 0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 33.0, i: 1.2, d: 0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 33.0, i: 1.2, d: 0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_7
    pid: {p: 33.0, i: 1.2, d: 0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_8
    pid: {p: 33.0, i: 1.2, d: 0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_9
    pid: {p: 33.0, i: 1.2, d: 0}

